visitor -> molinex "Explores product information and requests commercial contact through Molinex."
administrator -> molinex "Uses Molinex to administer users and supervise rice mill operations."
maintenanceTechnician -> molinex "Uses Molinex to manage machines, maintenance, anomalies and alerts."
productionOperator -> molinex "Uses Molinex to record production, quality and waste information."
sensorGateway -> molinex "Sends planned operational readings to Molinex." "HTTPS or MQTT"
molinex -> notificationService "Sends planned account and operational alert notifications to." "HTTPS API or SMTP"

visitor -> molinex.landingPage "Explores product information using" "HTTPS"
administrator -> molinex.webApplication "Administers users and supervises operations using" "HTTPS"
maintenanceTechnician -> molinex.webApplication "Manages machines, maintenance and alerts using" "HTTPS"
productionOperator -> molinex.webApplication "Records production and quality information using" "HTTPS"
molinex.landingPage -> molinex.apiApplication "Submits commercial inquiries to" "JSON/HTTPS REST"
molinex.webApplication -> molinex.apiApplication "Manages and queries operational information through" "JSON/HTTPS REST"
sensorGateway -> molinex.apiApplication "Sends planned operational readings to" "HTTPS or MQTT"
molinex.apiApplication -> notificationService "Sends planned account and operational alert notifications through" "HTTPS API or SMTP"
molinex.apiApplication -> molinex.database "Reads from and writes to" "JDBC/SQL"

visitor -> molinex.webApplication.commercialFeature "Uses"
administrator -> molinex.webApplication.identityFeature "Uses"
administrator -> molinex.webApplication.reportingFeature "Uses"
maintenanceTechnician -> molinex.webApplication.maintenanceFeature "Uses"
maintenanceTechnician -> molinex.webApplication.intelligenceFeature "Uses"
productionOperator -> molinex.webApplication.productionFeature "Uses"
productionOperator -> molinex.webApplication.qualityFeature "Uses"
molinex.webApplication.commercialFeature -> molinex.webApplication.frontendShared "Uses shared concerns from"
molinex.webApplication.identityFeature -> molinex.webApplication.frontendShared "Uses shared concerns from"
molinex.webApplication.productionFeature -> molinex.webApplication.frontendShared "Uses shared concerns from"
molinex.webApplication.qualityFeature -> molinex.webApplication.frontendShared "Uses shared concerns from"
molinex.webApplication.maintenanceFeature -> molinex.webApplication.frontendShared "Uses shared concerns from"
molinex.webApplication.intelligenceFeature -> molinex.webApplication.frontendShared "Uses shared concerns from"
molinex.webApplication.reportingFeature -> molinex.webApplication.frontendShared "Uses shared concerns from"
molinex.webApplication.commercialFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.identityFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.productionFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.qualityFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.maintenanceFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.intelligenceFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.webApplication.reportingFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"

molinex.webApplication.commercialPresentation -> molinex.webApplication.commercialApplication "Dispatches actions and reads state from"
molinex.webApplication.commercialApplication -> molinex.webApplication.commercialDomain "Uses models and validation rules from"
molinex.webApplication.commercialApplication -> molinex.webApplication.commercialInfrastructure "Loads plans and submits inquiries through"
molinex.webApplication.commercialInfrastructure -> molinex.webApplication.commercialDomain "Maps API resources to"
molinex.webApplication.commercialInfrastructure -> molinex.apiApplication "Invokes commercial endpoints on" "JSON/HTTPS REST"

molinex.webApplication.identityPresentation -> molinex.webApplication.identityApplication "Dispatches identity actions and reads state from"
molinex.webApplication.identityApplication -> molinex.webApplication.identityDomain "Uses identity models and policies from"
molinex.webApplication.identityApplication -> molinex.webApplication.identityInfrastructure "Authenticates and loads identity data through"
molinex.webApplication.identityInfrastructure -> molinex.webApplication.identityDomain "Maps API resources to"
molinex.webApplication.identityInfrastructure -> molinex.apiApplication "Invokes identity endpoints on" "JSON/HTTPS REST"

molinex.webApplication.productionPresentation -> molinex.webApplication.productionApplication "Dispatches production actions and reads state from"
molinex.webApplication.productionApplication -> molinex.webApplication.productionDomain "Uses production models from"
molinex.webApplication.productionApplication -> molinex.webApplication.productionInfrastructure "Loads and persists production data through"
molinex.webApplication.productionInfrastructure -> molinex.webApplication.productionDomain "Maps API resources to"
molinex.webApplication.productionInfrastructure -> molinex.apiApplication "Invokes production endpoints on" "JSON/HTTPS REST"

molinex.webApplication.qualityPresentation -> molinex.webApplication.qualityApplication "Dispatches quality actions and reads state from"
molinex.webApplication.qualityApplication -> molinex.webApplication.qualityDomain "Uses quality and yield models from"
molinex.webApplication.qualityApplication -> molinex.webApplication.qualityInfrastructure "Loads and persists quality data through"
molinex.webApplication.qualityInfrastructure -> molinex.webApplication.qualityDomain "Maps API resources to"
molinex.webApplication.qualityInfrastructure -> molinex.apiApplication "Invokes quality endpoints on" "JSON/HTTPS REST"

molinex.webApplication.maintenancePresentation -> molinex.webApplication.maintenanceApplication "Dispatches maintenance actions and reads state from"
molinex.webApplication.maintenanceApplication -> molinex.webApplication.maintenanceDomain "Uses asset and maintenance models from"
molinex.webApplication.maintenanceApplication -> molinex.webApplication.maintenanceInfrastructure "Loads and persists maintenance data through"
molinex.webApplication.maintenanceInfrastructure -> molinex.webApplication.maintenanceDomain "Maps API resources to"
molinex.webApplication.maintenanceInfrastructure -> molinex.apiApplication "Invokes maintenance endpoints on" "JSON/HTTPS REST"

molinex.webApplication.intelligencePresentation -> molinex.webApplication.intelligenceApplication "Dispatches monitoring actions and reads state from"
molinex.webApplication.intelligenceApplication -> molinex.webApplication.intelligenceDomain "Uses operational intelligence models from"
molinex.webApplication.intelligenceApplication -> molinex.webApplication.intelligenceInfrastructure "Loads readings, anomalies and alerts through"
molinex.webApplication.intelligenceInfrastructure -> molinex.webApplication.intelligenceDomain "Maps API resources to"
molinex.webApplication.intelligenceInfrastructure -> molinex.apiApplication "Invokes intelligence endpoints on" "JSON/HTTPS REST"

molinex.webApplication.reportingPresentation -> molinex.webApplication.reportingApplication "Dispatches report queries and reads state from"
molinex.webApplication.reportingApplication -> molinex.webApplication.reportingDomain "Uses reporting read models from"
molinex.webApplication.reportingApplication -> molinex.webApplication.reportingInfrastructure "Loads summaries, reports and trends through"
molinex.webApplication.reportingInfrastructure -> molinex.webApplication.reportingDomain "Maps projections to"
molinex.webApplication.reportingInfrastructure -> molinex.apiApplication "Invokes reporting endpoints on" "JSON/HTTPS REST"

molinex.webApplication.sharedPresentation -> molinex.webApplication.sharedApplication "Reads session and application context from"
molinex.webApplication.sharedApplication -> molinex.webApplication.sharedDomain "Uses shared values from"
molinex.webApplication.sharedApplication -> molinex.webApplication.sharedInfrastructure "Uses authenticated HTTP and error handling from"
molinex.webApplication.sharedInfrastructure -> molinex.apiApplication "Configures requests to" "JSON/HTTPS REST"

molinex.landingPage -> molinex.apiApplication.commercialModule "Uses"
molinex.webApplication -> molinex.apiApplication.identityModule "Uses"
molinex.webApplication -> molinex.apiApplication.productionModule "Uses"
molinex.webApplication -> molinex.apiApplication.qualityModule "Uses"
molinex.webApplication -> molinex.apiApplication.maintenanceModule "Uses"
molinex.webApplication -> molinex.apiApplication.intelligenceModule "Uses"
molinex.webApplication -> molinex.apiApplication.reportingModule "Uses"
sensorGateway -> molinex.apiApplication.intelligenceModule "Sends measurements to" "HTTPS or MQTT"
molinex.apiApplication.identityModule -> notificationService "Sends account notifications through"
molinex.apiApplication.intelligenceModule -> notificationService "Sends operational alerts through"
molinex.apiApplication.productionModule -> molinex.apiApplication.qualityModule "Publishes production events"
molinex.apiApplication.qualityModule -> molinex.apiApplication.intelligenceModule "Publishes quality deviations"
molinex.apiApplication.maintenanceModule -> molinex.apiApplication.intelligenceModule "Publishes asset events"
molinex.apiApplication.intelligenceModule -> molinex.apiApplication.maintenanceModule "Publishes anomalies"
molinex.apiApplication.productionModule -> molinex.apiApplication.reportingModule "Publishes production events"
molinex.apiApplication.qualityModule -> molinex.apiApplication.reportingModule "Publishes quality events"
molinex.apiApplication.maintenanceModule -> molinex.apiApplication.reportingModule "Publishes maintenance events"
molinex.apiApplication.intelligenceModule -> molinex.apiApplication.reportingModule "Publishes alert events"
molinex.apiApplication.productionModule -> molinex.apiApplication.sharedKernel "Uses shared values"
molinex.apiApplication.qualityModule -> molinex.apiApplication.sharedKernel "Uses shared values"
molinex.apiApplication.commercialModule -> molinex.database "Owns commercial inquiry and plan data in" "JDBC/SQL"
molinex.apiApplication.identityModule -> molinex.database "Owns identity and authorization data in" "JDBC/SQL"
molinex.apiApplication.productionModule -> molinex.database "Owns production data in" "JDBC/SQL"
molinex.apiApplication.qualityModule -> molinex.database "Owns quality and yield data in" "JDBC/SQL"
molinex.apiApplication.maintenanceModule -> molinex.database "Owns machine and maintenance data in" "JDBC/SQL"
molinex.apiApplication.intelligenceModule -> molinex.database "Owns reading, anomaly and alert data in" "JDBC/SQL"
molinex.apiApplication.reportingModule -> molinex.database "Owns reporting projections in" "JDBC/SQL"

molinex.landingPage -> molinex.apiApplication.commercialInterfaces "Submits plan and inquiry requests to" "JSON/HTTPS REST"
molinex.apiApplication.commercialInterfaces -> molinex.apiApplication.commercialApplication "Delegates commands and queries to"
molinex.apiApplication.commercialApplication -> molinex.apiApplication.commercialDomain "Uses aggregates, events and repository ports from"
molinex.apiApplication.commercialInfrastructure -> molinex.apiApplication.commercialDomain "Implements repository ports defined by"
molinex.apiApplication.commercialInfrastructure -> molinex.database "Persists commercial data in" "JDBC/SQL"

molinex.webApplication -> molinex.apiApplication.identityInterfaces "Invokes identity operations on" "JSON/HTTPS REST"
molinex.apiApplication.identityInterfaces -> molinex.apiApplication.identityApplication "Delegates commands and queries to"
molinex.apiApplication.identityApplication -> molinex.apiApplication.identityDomain "Uses aggregates, policies and repository ports from"
molinex.apiApplication.identityInfrastructure -> molinex.apiApplication.identityDomain "Implements security and repository ports defined by"
molinex.apiApplication.identityInfrastructure -> molinex.database "Persists identity data in" "JDBC/SQL"
molinex.apiApplication.identityInfrastructure -> notificationService "Delivers account notifications through" "HTTPS API or SMTP"

molinex.webApplication -> molinex.apiApplication.productionInterfaces "Invokes production operations on" "JSON/HTTPS REST"
molinex.apiApplication.productionInterfaces -> molinex.apiApplication.productionApplication "Delegates commands and queries to"
molinex.apiApplication.productionApplication -> molinex.apiApplication.productionDomain "Uses aggregates, events and repository ports from"
molinex.apiApplication.productionInfrastructure -> molinex.apiApplication.productionDomain "Implements repository and event publication ports defined by"
molinex.apiApplication.productionInfrastructure -> molinex.database "Persists production data in" "JDBC/SQL"

molinex.webApplication -> molinex.apiApplication.qualityInterfaces "Invokes quality operations on" "JSON/HTTPS REST"
molinex.apiApplication.qualityInterfaces -> molinex.apiApplication.qualityApplication "Delegates commands and queries to"
molinex.apiApplication.qualityApplication -> molinex.apiApplication.qualityDomain "Uses aggregates, events and repository ports from"
molinex.apiApplication.qualityInfrastructure -> molinex.apiApplication.qualityDomain "Implements repository and event publication ports defined by"
molinex.apiApplication.qualityInfrastructure -> molinex.database "Persists quality and yield data in" "JDBC/SQL"

molinex.webApplication -> molinex.apiApplication.maintenanceInterfaces "Invokes maintenance operations on" "JSON/HTTPS REST"
molinex.apiApplication.maintenanceInterfaces -> molinex.apiApplication.maintenanceApplication "Delegates commands and queries to"
molinex.apiApplication.maintenanceApplication -> molinex.apiApplication.maintenanceDomain "Uses aggregates, events and repository ports from"
molinex.apiApplication.maintenanceInfrastructure -> molinex.apiApplication.maintenanceDomain "Implements repository and event publication ports defined by"
molinex.apiApplication.maintenanceInfrastructure -> molinex.database "Persists asset and maintenance data in" "JDBC/SQL"

molinex.webApplication -> molinex.apiApplication.intelligenceInterfaces "Invokes monitoring operations on" "JSON/HTTPS REST"
sensorGateway -> molinex.apiApplication.intelligenceInterfaces "Sends operational readings to" "HTTPS or MQTT"
molinex.apiApplication.intelligenceInterfaces -> molinex.apiApplication.intelligenceApplication "Delegates commands and queries to"
molinex.apiApplication.intelligenceApplication -> molinex.apiApplication.intelligenceDomain "Uses aggregates, criteria, events and repository ports from"
molinex.apiApplication.intelligenceInfrastructure -> molinex.apiApplication.intelligenceDomain "Implements telemetry, repository and notification ports defined by"
molinex.apiApplication.intelligenceInfrastructure -> molinex.database "Persists readings, anomalies and alerts in" "JDBC/SQL"
molinex.apiApplication.intelligenceInfrastructure -> notificationService "Delivers operational alerts through" "HTTPS API"

molinex.webApplication -> molinex.apiApplication.reportingInterfaces "Invokes reporting queries on" "JSON/HTTPS REST"
molinex.apiApplication.reportingInterfaces -> molinex.apiApplication.reportingApplication "Delegates report queries to"
molinex.apiApplication.reportingApplication -> molinex.apiApplication.reportingDomain "Uses read models and projection repository ports from"
molinex.apiApplication.reportingInfrastructure -> molinex.apiApplication.reportingDomain "Implements projection repository ports defined by"
molinex.apiApplication.reportingInfrastructure -> molinex.database "Reads and stores reporting projections in" "JDBC/SQL"

molinex.apiApplication.productionDomain -> molinex.apiApplication.sharedKernelDomain "Uses Weight and MeasurementUnit from"
molinex.apiApplication.qualityDomain -> molinex.apiApplication.sharedKernelDomain "Uses Weight and MeasurementUnit from"
