visitor -> molinex "Explores product information and requests commercial contact through Molinex."
administrator -> molinex "Uses Molinex to administer users and supervise rice mill operations."
maintenanceTechnician -> molinex "Uses Molinex to manage machines, maintenance, anomalies and alerts."
productionOperator -> molinex "Uses Molinex to record production, quality and waste information."
sensorGateway -> molinex "Sends planned operational readings to Molinex." "HTTPS or MQTT"
molinex -> notificationService "Sends planned account and operational alert notifications to." "HTTPS API or SMTP"

visitor -> molinex.landingPage "Explores product information using" "HTTPS"
administrator -> molinex.spa "Administers users and supervises operations using" "HTTPS"
maintenanceTechnician -> molinex.spa "Manages machines, maintenance and alerts using" "HTTPS"
productionOperator -> molinex.spa "Records production and quality information using" "HTTPS"
molinex.landingPage -> molinex.apiApplication "Submits commercial inquiries to" "JSON/HTTPS REST"
molinex.webApplication -> molinex.spa "Delivers the compiled application to the user's browser" "HTTPS"
molinex.spa -> molinex.apiApplication "Manages and queries operational information through" "JSON/HTTPS REST"
sensorGateway -> molinex.apiApplication "Sends planned operational readings to" "HTTPS or MQTT"
molinex.apiApplication -> notificationService "Sends planned account and operational alert notifications through" "HTTPS API or SMTP"
molinex.apiApplication -> molinex.database "Reads from and writes to" "JDBC/SQL"

visitor -> molinex.spa.commercialFeature "Uses"
administrator -> molinex.spa.identityFeature "Uses"
administrator -> molinex.spa.reportingFeature "Uses"
maintenanceTechnician -> molinex.spa.maintenanceFeature "Uses"
maintenanceTechnician -> molinex.spa.intelligenceFeature "Uses"
productionOperator -> molinex.spa.productionFeature "Uses"
productionOperator -> molinex.spa.qualityFeature "Uses"
molinex.spa.commercialFeature -> molinex.spa.frontendShared "Uses shared concerns from"
molinex.spa.identityFeature -> molinex.spa.frontendShared "Uses shared concerns from"
molinex.spa.productionFeature -> molinex.spa.frontendShared "Uses shared concerns from"
molinex.spa.qualityFeature -> molinex.spa.frontendShared "Uses shared concerns from"
molinex.spa.maintenanceFeature -> molinex.spa.frontendShared "Uses shared concerns from"
molinex.spa.intelligenceFeature -> molinex.spa.frontendShared "Uses shared concerns from"
molinex.spa.reportingFeature -> molinex.spa.frontendShared "Uses shared concerns from"
molinex.spa.commercialFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.spa.identityFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.spa.productionFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.spa.qualityFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.spa.maintenanceFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.spa.intelligenceFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"
molinex.spa.reportingFeature -> molinex.apiApplication "Uses" "JSON/HTTPS REST"

molinex.spa.commercialPresentation -> molinex.spa.commercialApplication "Dispatches actions and reads state from"
molinex.spa.commercialApplication -> molinex.spa.commercialDomain "Uses models and validation rules from"
molinex.spa.commercialApplication -> molinex.spa.commercialInfrastructure "Loads plans and submits inquiries through"
molinex.spa.commercialInfrastructure -> molinex.spa.commercialDomain "Maps API resources to"
molinex.spa.commercialInfrastructure -> molinex.apiApplication "Invokes commercial endpoints on" "JSON/HTTPS REST"

molinex.spa.identityPresentation -> molinex.spa.identityApplication "Dispatches identity actions and reads state from"
molinex.spa.identityApplication -> molinex.spa.identityDomain "Uses identity models and policies from"
molinex.spa.identityApplication -> molinex.spa.identityInfrastructure "Authenticates and loads identity data through"
molinex.spa.identityInfrastructure -> molinex.spa.identityDomain "Maps API resources to"
molinex.spa.identityInfrastructure -> molinex.apiApplication "Invokes identity endpoints on" "JSON/HTTPS REST"

molinex.spa.productionPresentation -> molinex.spa.productionApplication "Dispatches production actions and reads state from"
molinex.spa.productionApplication -> molinex.spa.productionDomain "Uses production models from"
molinex.spa.productionApplication -> molinex.spa.productionInfrastructure "Loads and persists production data through"
molinex.spa.productionInfrastructure -> molinex.spa.productionDomain "Maps API resources to"
molinex.spa.productionInfrastructure -> molinex.apiApplication "Invokes production endpoints on" "JSON/HTTPS REST"

molinex.spa.qualityPresentation -> molinex.spa.qualityApplication "Dispatches quality actions and reads state from"
molinex.spa.qualityApplication -> molinex.spa.qualityDomain "Uses quality and yield models from"
molinex.spa.qualityApplication -> molinex.spa.qualityInfrastructure "Loads and persists quality data through"
molinex.spa.qualityInfrastructure -> molinex.spa.qualityDomain "Maps API resources to"
molinex.spa.qualityInfrastructure -> molinex.apiApplication "Invokes quality endpoints on" "JSON/HTTPS REST"

molinex.spa.maintenancePresentation -> molinex.spa.maintenanceApplication "Dispatches maintenance actions and reads state from"
molinex.spa.maintenanceApplication -> molinex.spa.maintenanceDomain "Uses asset and maintenance models from"
molinex.spa.maintenanceApplication -> molinex.spa.maintenanceInfrastructure "Loads and persists maintenance data through"
molinex.spa.maintenanceInfrastructure -> molinex.spa.maintenanceDomain "Maps API resources to"
molinex.spa.maintenanceInfrastructure -> molinex.apiApplication "Invokes maintenance endpoints on" "JSON/HTTPS REST"

molinex.spa.intelligencePresentation -> molinex.spa.intelligenceApplication "Dispatches monitoring actions and reads state from"
molinex.spa.intelligenceApplication -> molinex.spa.intelligenceDomain "Uses operational intelligence models from"
molinex.spa.intelligenceApplication -> molinex.spa.intelligenceInfrastructure "Loads readings, anomalies and alerts through"
molinex.spa.intelligenceInfrastructure -> molinex.spa.intelligenceDomain "Maps API resources to"
molinex.spa.intelligenceInfrastructure -> molinex.apiApplication "Invokes intelligence endpoints on" "JSON/HTTPS REST"

molinex.spa.reportingPresentation -> molinex.spa.reportingApplication "Dispatches report queries and reads state from"
molinex.spa.reportingApplication -> molinex.spa.reportingDomain "Uses reporting read models from"
molinex.spa.reportingApplication -> molinex.spa.reportingInfrastructure "Loads summaries, reports and trends through"
molinex.spa.reportingInfrastructure -> molinex.spa.reportingDomain "Maps projections to"
molinex.spa.reportingInfrastructure -> molinex.apiApplication "Invokes reporting endpoints on" "JSON/HTTPS REST"

molinex.spa.sharedPresentation -> molinex.spa.sharedApplication "Reads session and application context from"
molinex.spa.sharedApplication -> molinex.spa.sharedDomain "Uses shared values from"
molinex.spa.sharedApplication -> molinex.spa.sharedInfrastructure "Uses authenticated HTTP and error handling from"
molinex.spa.sharedInfrastructure -> molinex.apiApplication "Configures requests to" "JSON/HTTPS REST"

molinex.landingPage -> molinex.apiApplication.commercialModule "Uses"
molinex.spa -> molinex.apiApplication.identityModule "Uses"
molinex.spa -> molinex.apiApplication.productionModule "Uses"
molinex.spa -> molinex.apiApplication.qualityModule "Uses"
molinex.spa -> molinex.apiApplication.maintenanceModule "Uses"
molinex.spa -> molinex.apiApplication.intelligenceModule "Uses"
molinex.spa -> molinex.apiApplication.reportingModule "Uses"
sensorGateway -> molinex.apiApplication.intelligenceModule "Sends measurements to" "HTTPS or MQTT"
molinex.apiApplication.identityModule -> notificationService "Sends account notifications through"
molinex.apiApplication.intelligenceModule -> notificationService "Sends operational alerts through"
molinex.apiApplication.productionModule -> molinex.apiApplication.qualityModule "Publishes production events"
molinex.apiApplication.qualityModule -> molinex.apiApplication.intelligenceModule "Publishes quality deviations"
molinex.apiApplication.maintenanceModule -> molinex.apiApplication.intelligenceModule "Publishes asset events"
molinex.apiApplication.intelligenceModule -> molinex.apiApplication.maintenanceModule "Publishes anomalies"
molinex.apiApplication.productionModule -> molinex.apiApplication.reportingModule "Publishes production events"
molinex.apiApplication.qualityModule -> molinex.apiApplication.reportingModule "Publishes quality events"
molinex.apiApplication.maintenanceModule -> molinex.apiApplication.reportingModule "Publishes maintenance events"
molinex.apiApplication.intelligenceModule -> molinex.apiApplication.reportingModule "Publishes alert events"
molinex.apiApplication.productionModule -> molinex.apiApplication.sharedKernel "Uses shared values"
molinex.apiApplication.qualityModule -> molinex.apiApplication.sharedKernel "Uses shared values"
molinex.apiApplication.commercialModule -> molinex.database "Owns commercial inquiry and plan data in" "JDBC/SQL"
molinex.apiApplication.identityModule -> molinex.database "Owns identity and authorization data in" "JDBC/SQL"
molinex.apiApplication.productionModule -> molinex.database "Owns production data in" "JDBC/SQL"
molinex.apiApplication.qualityModule -> molinex.database "Owns quality and yield data in" "JDBC/SQL"
molinex.apiApplication.maintenanceModule -> molinex.database "Owns machine and maintenance data in" "JDBC/SQL"
molinex.apiApplication.intelligenceModule -> molinex.database "Owns reading, anomaly and alert data in" "JDBC/SQL"
molinex.apiApplication.reportingModule -> molinex.database "Owns reporting projections in" "JDBC/SQL"

molinex.landingPage -> molinex.apiApplication.commercialInterfaces "Submits plan and inquiry requests to" "JSON/HTTPS REST"
molinex.apiApplication.commercialInterfaces -> molinex.apiApplication.commercialApplication "Delegates commands and queries to"
molinex.apiApplication.commercialApplication -> molinex.apiApplication.commercialDomain "Uses aggregates, events and repository ports from"
molinex.apiApplication.commercialInfrastructure -> molinex.apiApplication.commercialDomain "Implements repository ports defined by"
molinex.apiApplication.commercialInfrastructure -> molinex.database "Persists commercial data in" "JDBC/SQL"

molinex.spa -> molinex.apiApplication.identityInterfaces "Invokes identity operations on" "JSON/HTTPS REST"
molinex.apiApplication.identityInterfaces -> molinex.apiApplication.identityApplication "Delegates commands and queries to"
molinex.apiApplication.identityApplication -> molinex.apiApplication.identityDomain "Uses aggregates, policies and repository ports from"
molinex.apiApplication.identityInfrastructure -> molinex.apiApplication.identityDomain "Implements security and repository ports defined by"
molinex.apiApplication.identityInfrastructure -> molinex.database "Persists identity data in" "JDBC/SQL"
molinex.apiApplication.identityInfrastructure -> notificationService "Delivers account notifications through" "HTTPS API or SMTP"

molinex.spa -> molinex.apiApplication.productionInterfaces "Invokes production operations on" "JSON/HTTPS REST"
molinex.apiApplication.productionInterfaces -> molinex.apiApplication.productionApplication "Delegates commands and queries to"
molinex.apiApplication.productionApplication -> molinex.apiApplication.productionDomain "Uses aggregates, events and repository ports from"
molinex.apiApplication.productionInfrastructure -> molinex.apiApplication.productionDomain "Implements repository and event publication ports defined by"
molinex.apiApplication.productionInfrastructure -> molinex.database "Persists production data in" "JDBC/SQL"

molinex.spa -> molinex.apiApplication.qualityInterfaces "Invokes quality operations on" "JSON/HTTPS REST"
molinex.apiApplication.qualityInterfaces -> molinex.apiApplication.qualityApplication "Delegates commands and queries to"
molinex.apiApplication.qualityApplication -> molinex.apiApplication.qualityDomain "Uses aggregates, events and repository ports from"
molinex.apiApplication.qualityInfrastructure -> molinex.apiApplication.qualityDomain "Implements repository and event publication ports defined by"
molinex.apiApplication.qualityInfrastructure -> molinex.database "Persists quality and yield data in" "JDBC/SQL"

molinex.spa -> molinex.apiApplication.maintenanceInterfaces "Invokes maintenance operations on" "JSON/HTTPS REST"
molinex.apiApplication.maintenanceInterfaces -> molinex.apiApplication.maintenanceApplication "Delegates commands and queries to"
molinex.apiApplication.maintenanceApplication -> molinex.apiApplication.maintenanceDomain "Uses aggregates, events and repository ports from"
molinex.apiApplication.maintenanceInfrastructure -> molinex.apiApplication.maintenanceDomain "Implements repository and event publication ports defined by"
molinex.apiApplication.maintenanceInfrastructure -> molinex.database "Persists asset and maintenance data in" "JDBC/SQL"

molinex.spa -> molinex.apiApplication.intelligenceInterfaces "Invokes monitoring operations on" "JSON/HTTPS REST"
sensorGateway -> molinex.apiApplication.intelligenceInterfaces "Sends operational readings to" "HTTPS or MQTT"
molinex.apiApplication.intelligenceInterfaces -> molinex.apiApplication.intelligenceApplication "Delegates commands and queries to"
molinex.apiApplication.intelligenceApplication -> molinex.apiApplication.intelligenceDomain "Uses aggregates, criteria, events and repository ports from"
molinex.apiApplication.intelligenceInfrastructure -> molinex.apiApplication.intelligenceDomain "Implements telemetry, repository and notification ports defined by"
molinex.apiApplication.intelligenceInfrastructure -> molinex.database "Persists readings, anomalies and alerts in" "JDBC/SQL"
molinex.apiApplication.intelligenceInfrastructure -> notificationService "Delivers operational alerts through" "HTTPS API"

molinex.spa -> molinex.apiApplication.reportingInterfaces "Invokes reporting queries on" "JSON/HTTPS REST"
molinex.apiApplication.reportingInterfaces -> molinex.apiApplication.reportingApplication "Delegates report queries to"
molinex.apiApplication.reportingApplication -> molinex.apiApplication.reportingDomain "Uses read models and projection repository ports from"
molinex.apiApplication.reportingInfrastructure -> molinex.apiApplication.reportingDomain "Implements projection repository ports defined by"
molinex.apiApplication.reportingInfrastructure -> molinex.database "Reads and stores reporting projections in" "JDBC/SQL"

molinex.apiApplication.productionDomain -> molinex.apiApplication.sharedKernelDomain "Uses Weight and MeasurementUnit from"
molinex.apiApplication.qualityDomain -> molinex.apiApplication.sharedKernelDomain "Uses Weight and MeasurementUnit from"
